package com.daegonner.lms.reward;

import com.daegonner.lms.util.ItemFactory;
import org.bukkit.Location;
import org.bukkit.block.Chest;
import org.bukkit.block.DoubleChest;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;

/**
 * When granted, provides an item generated by the {@link ItemFactory}.
 */
public class ItemReward implements Reward {

    private final ItemFactory itemFactory;

    public ItemReward(ItemFactory itemFactory) {
        this.itemFactory = itemFactory;
    }

    @Override
    public void grant(Player player, Inventory inventory) {
        Location location = getLocation(inventory, player.getLocation());
        inventory.addItem(itemFactory.create()).forEach((amount, item) -> {
            item.setAmount(amount);
            player.getWorld().dropItemNaturally(location, item);
        });
    }

    /**
     * Attempts to find the location of an {@link Inventory}, otherwise uses
     * the default location.
     *
     * @param inventory the {@link Inventory} to get the location of.
     * @param def       the default location.
     * @return the inventory location.
     */
    private Location getLocation(Inventory inventory, Location def) {
        if (inventory.getHolder() instanceof Chest) {
            return ((Chest) inventory.getHolder()).getLocation();
        }

        if (inventory.getHolder() instanceof DoubleChest) {
            return ((DoubleChest) inventory.getHolder()).getLocation();
        }

        return def;
    }
}
