config-version: 1
messages:
  lobby-start: "&eLMS lobby is now available to join! &d/lms join"
  lobby-announce: "&eLMS will start in &d{time}&e. Join with: &d/lms join"
  game-teleported: "&eYou have been teleported into LMS"
  game-warmup: "&eProtection ends in &d{time}"
settings:
  announcement-times: [1, 2, 3, 4, 5, 10, 30, 60, 120, 300, 600, 900, 1800]
arena-settings:
  default:
    disable-hunger: true
    kill-money:
      min: 2000
      max: 5000
    rewards:
    - material: diamond_block
      amount:
        max: 512
        min: 64
    - material: diamond_sword
      chance: 0.25
      enchantments:
        sharpness: 5
        fire_aspect: 2
      name: "&dLMS Sword"
      lore:
      - "&eReceived by winning LMS"
    - type: command
      sender: console
      command: "tell {player} Congratulations!"
    inventory:
    - material: diamond_sword
      enchantments:
        sharpness: 2
    - material: potion
      potion-type: instant_heal
      upgraded: true
      splash: true
      amount: 24
    armour:
      head:
        material: diamond_helmet
        enchantments:
          protection: 2
          unbreaking: 3
      chest:
        material: diamond_chestplate
        enchantments:
          protection: 2
          unbreaking: 3
      legs:
        material: diamond_leggings
        enchantments:
          protection: 2
          unbreaking: 3
      boots:
        material: diamond_boots
        enchantments:
          protection: 2
          unbreaking: 3