config-version: 1
messages:
  reload: "&eSettings successfully reloaded"
  lobby-start: "&eLMS lobby is now available to join! &d/lms join"
  lobby-countdown: "&eLMS will start in &d{time}&e. Join with: &d/lms join"
  lobby-failed-players: "&eLMS unable to start due to too low player interest"
  lobby-cancelled: "&eLMS lobby has been cancelled"
  lobby-non-existent: "&cNo LMS lobby exists"
  lobby-joined: "&eSuccessfully joined the LMS lobby"
  lobby-scheduled: "&eNext lobby scheduled to run in &d{time}"
  lobby-not-joined: "&cYou are currently not in the lobby"
  lobby-already-joined: "&cYou are already in the lobby"
  game-teleported: "&eYou have been teleported into LMS"
  game-warmup: "&eProtection ends in &d{time}"
  game-cancelled: "&eLMS has been cancelled"
  game-complete: "&d{player}&e has won the LMS!"
  game-running: "&cA game is already in progress"
  game-exit: "&eSuccessfully left the LMS game"
  game-exit-failed: "&cYou are not currently in an LMS game"
  game-non-existent: "&cNo LMS game exists"
  game-spectate: "&eYou are now spectating LMS"
  player-only-command: "&cThis command can only be executed by players"
  invalid-selection: "&cPlease create a valid cuboid selection with WorldEdit"
  arena-already-exists: "&cAn arena by that name already exists"
  arena-created: "&eArena &d{name}&e created"
  arena-renamed: "&eArena renamed to &d{name}"
  arena-name-size: "&cArena name is too long"
  arena-location-invalid: "&cYou are not within the arena region"
  arena-spawn-created: "&eSuccessfully created a new arena spawn point"
  arena-spawn-invalid: "&cA spawn by that ID does not exist"
  arena-spawn-deleted: "&eArena spawn successfully deleted"
  arena-region-updated: "&eArena region successfully updated"
  arena-deleted: "&eArena successfully deleted"
  arena-list-header: "&e&l -- Arenas -- "
  arena-list: "&d{id}&e. {arena}"
  arena-info: |
    &e&l -- Arena {arena} --
    &eRegion: {world} {minX},{minY},{minZ} -> {maxX},{maxY},{maxZ}
    {spawns}
  arena-info-spawn: "&eSpawn {id}: {x},{y},{z} yaw:{yaw} pitch:{pitch}"
settings:
  lobby-start: 10800
  lobby-countdown: 300
  announcement-times: [1, 2, 3, 4, 5, 10, 30, 60, 120, 300, 600, 900, 1800]
arena-settings:
  default:
    disable-hunger: true
    min-players: 2
    kill-money:
      min: 2000
      max: 5000
    rewards:
    - material: diamond_block
      amount:
        max: 512
        min: 64
    - material: diamond_sword
      chance: 0.25
      enchantments:
        sharpness: 5
        fire_aspect: 2
      name: "&dLMS Sword"
      lore:
      - "&eReceived by winning LMS"
    - type: command
      sender: console
      command: "tell {player} Congratulations!"
    inventory:
    - material: diamond_sword
      enchantments:
        sharpness: 2
    - material: potion
      potion-type: instant_heal
      upgraded: true
      splash: true
      amount: 24
    armour:
      head:
        material: diamond_helmet
        enchantments:
          protection: 2
          unbreaking: 3
      chest:
        material: diamond_chestplate
        enchantments:
          protection: 2
          unbreaking: 3
      legs:
        material: diamond_leggings
        enchantments:
          protection: 2
          unbreaking: 3
      boots:
        material: diamond_boots
        enchantments:
          protection: 2
          unbreaking: 3